// Generated by scripts/generate-design-manifest.mjs from each pack's
// catalog.json landing.style.preset — do not edit by hand. Regenerate
// with: npm run codegen:design-manifest.
//
// The catalog is the only authority for a pack's register: compose
// stamps it into the project's landing document, and these constants
// are the code configs' matching fallback pins (the document, carrying
// the user's restyle, still outranks them at resolve time).
import type { MarketingPresetName } from "@ui"

export const PACK_REGISTERS = {
    band: "broadside",
    care: "luxe-light",
    church: "hymnal",
    community: "atelier",
    dj: "mono-utility",
    estate: "brownstone",
    fitness: "chalk",
    "fitness-trainer": "monolith",
    "fitness-yoga": "atelier",
    folio: "editorial",
    "fund-index": "mono-utility",
    gala: "ballroom",
    launch: "dark-dev",
    nonprofit: "monolith",
    photography: "tourbook",
    "photography-music": "marquee",
    resume: "editorial",
    "resume-dev": "monolith",
    reunion: "picnic",
    saas: "monolith",
    services: "sitework",
    "services-emergency": "sitework",
    "services-recurring": "warm-boutique",
    single: "monolith",
    vows: "heirloom",
    wedding: "lanternlight",
} as const satisfies Record<string, MarketingPresetName>

export type RegisteredPackKey = keyof typeof PACK_REGISTERS
