package com.baseapp.android.config

import android.content.Context
import com.baseapp.android.auth.AuthMethod
import com.baseapp.android.auth.resolveAuthMethods
import java.net.URI
import java.util.Properties

enum class AppFlavor(val rawValue: String) {
    SANDBOX("sandbox"),
    DEV("dev"),
    PROD("prod");

    companion object {
        /** Maps the Gradle flavor name (BuildConfig.FLAVOR) to an AppFlavor. */
        fun resolve(gradleFlavor: String): AppFlavor = when (gradleFlavor.lowercase()) {
            "sandbox" -> SANDBOX
            "development" -> DEV
            "production" -> PROD
            // Fail closed to production if app flavor wiring is misconfigured.
            else -> PROD
        }
    }
}

/**
 * Mirrors AUTH_MODE / VITE_AUTH_MODE in env.manifest.json: 'local' uses the
 * bootstrap-generated dev JWT; 'builtin' uses the kernel's own auth API.
 */
enum class AuthMode(val rawValue: String) {
    LOCAL("local"),
    BUILTIN("builtin");

    companion object {
        fun fromRaw(raw: String): AuthMode? = entries.firstOrNull { it.rawValue == raw.lowercase() }
    }
}

data class AppConfig(
    val flavor: AppFlavor,
    /** Display name shown on the sign-in screen. Falls back to "App" when unset. */
    val appName: String,
    val graphqlUrl: String,
    val authMode: AuthMode,
    /**
     * Enabled sign-in methods (AUTH_METHODS, comma-separated), in configured
     * order — which is also the render order of the sign-in screen. Defaults
     * to email codes when unset (see resolveAuthMethods).
     */
    val authMethods: List<AuthMethod>,
    /** Where OAuth callbacks land (custom URL scheme back into the app). */
    val redirectUrl: String,
    /**
     * Sandbox only: the signed dev-principal JWT. Stamped into the built APK
     * by StampSandboxConfigTask from web/app/.env.local (generated by
     * `npm run bootstrap:env`); absent in the committed config.properties.
     */
    val localAuthToken: String?,
) {
    /**
     * The auth API endpoint is the auth__request__api function, which lives
     * next to the GraphQL function in every environment — the emulator and
     * the platform deployer treat all exports uniformly — so its URL is the
     * GraphQL URL with the trailing function name swapped. Null when the
     * GraphQL URL does not carry the well-known function name.
     */
    val authUrl: String?
        get() {
            if (!graphqlUrl.contains("graphql__request__api")) {
                return null
            }
            return graphqlUrl.replace("graphql__request__api", "auth__request__api")
        }
}

class ConfigLoaderException(message: String) : Exception(message)

object ConfigLoader {
    private const val CONFIG_ASSET = "config.properties"
    private const val LOCAL_CONFIG_ASSET = "config.local.properties"

    /**
     * Loads the flavor's committed config.properties asset, overlaid with the
     * build-generated config.local.properties (sandbox stamping) when present.
     */
    fun load(flavor: AppFlavor, context: Context, isEmulator: Boolean = isProbablyEmulator()): AppConfig {
        val values = mutableMapOf<String, String>()
        val properties = Properties()
        try {
            context.assets.open(CONFIG_ASSET).use(properties::load)
        } catch (error: Exception) {
            throw ConfigLoaderException("Missing bundled config asset: $CONFIG_ASSET.")
        }
        try {
            context.assets.open(LOCAL_CONFIG_ASSET).use(properties::load)
        } catch (_: Exception) {
            // Generated overlay only exists for stamped sandbox builds.
        }
        for (key in properties.stringPropertyNames()) {
            values[key] = properties.getProperty(key, "")
        }
        return parse(flavor, values, isEmulator, isClientOnly = ActivePack.isClientOnly)
    }

    /**
     * Client-only packs (blank, pong) build with an empty backend config —
     * there is no backend to point the app at, and their surfaces never touch
     * the network — so boot on a harmless local-mode placeholder instead of
     * failing closed. When real values are stamped (an agent upgraded the
     * project to a backend pack and redeployed), the strict path wins again.
     */
    fun clientOnlyPlaceholder(flavor: AppFlavor, values: Map<String, String>): AppConfig = AppConfig(
        flavor = flavor,
        appName = optionalString("APP_NAME", values) ?: "App",
        graphqlUrl = "https://client-only.invalid/graphql",
        authMode = AuthMode.LOCAL,
        authMethods = resolveAuthMethods(optionalString("AUTH_METHODS", values)),
        redirectUrl = optionalString("AUTH_REDIRECT_URL", values) ?: "baseapp://auth/callback",
        localAuthToken = optionalString("LOCAL_AUTH_TOKEN", values),
    )

    fun parse(
        flavor: AppFlavor,
        values: Map<String, String>,
        isEmulator: Boolean = false,
        isClientOnly: Boolean,
    ): AppConfig = try {
        parse(flavor, values, isEmulator)
    } catch (error: ConfigLoaderException) {
        if (isClientOnly) clientOnlyPlaceholder(flavor, values) else throw error
    }

    fun parse(
        flavor: AppFlavor,
        values: Map<String, String>,
        isEmulator: Boolean = false,
    ): AppConfig {
        val graphqlRaw = requiredString("GRAPHQL_URL", values)
        val authModeRaw = requiredString("AUTH_MODE", values)
        val redirectRaw = requiredString("AUTH_REDIRECT_URL", values)
        val appName = optionalString("APP_NAME", values) ?: "App"

        val authMode = AuthMode.fromRaw(authModeRaw)
            ?: throw ConfigLoaderException("Missing configuration value for key: AUTH_MODE.")

        val graphqlUrl = if (flavor == AppFlavor.SANDBOX) {
            rewriteSandboxHost(
                graphqlRaw,
                isEmulator = isEmulator,
                lanHost = optionalString("LOCAL_LAN_HOST", values),
            )
        } else {
            graphqlRaw
        }

        return AppConfig(
            flavor = flavor,
            appName = appName,
            graphqlUrl = graphqlUrl,
            authMode = authMode,
            authMethods = resolveAuthMethods(optionalString("AUTH_METHODS", values)),
            redirectUrl = redirectRaw,
            localAuthToken = optionalString("LOCAL_AUTH_TOKEN", values),
        )
    }

    /**
     * Sandbox twin of the iOS LAN-IP rewrite: the local emulator stack binds
     * to the host machine, which an Android emulator reaches at 10.0.2.2 and a
     * physical device reaches at the host's LAN IP (stamped at build time).
     */
    fun rewriteSandboxHost(rawUrl: String, isEmulator: Boolean, lanHost: String?): String {
        val parsed = try {
            URI(rawUrl)
        } catch (_: Exception) {
            return rawUrl
        }
        if (parsed.host !in listOf("127.0.0.1", "localhost")) {
            return rawUrl
        }
        val replacementHost = when {
            isEmulator -> "10.0.2.2"
            !lanHost.isNullOrEmpty() -> lanHost
            else -> return rawUrl
        }
        return URI(
            parsed.scheme,
            null,
            replacementHost,
            parsed.port,
            parsed.path,
            parsed.query,
            parsed.fragment,
        ).toString()
    }

    /** Best-effort emulator detection (pure so tests can exercise both paths). */
    fun isProbablyEmulator(
        fingerprint: String = android.os.Build.FINGERPRINT,
        model: String = android.os.Build.MODEL,
        hardware: String = android.os.Build.HARDWARE,
    ): Boolean {
        return fingerprint.startsWith("generic")
            || fingerprint.contains("emulator", ignoreCase = true)
            || model.contains("sdk_gphone", ignoreCase = true)
            || hardware.contains("goldfish", ignoreCase = true)
            || hardware.contains("ranchu", ignoreCase = true)
    }

    private fun requiredString(key: String, values: Map<String, String>): String {
        val value = values[key]
        if (value.isNullOrEmpty()) {
            throw ConfigLoaderException("Missing configuration value for key: $key.")
        }
        return value
    }

    private fun optionalString(key: String, values: Map<String, String>): String? {
        val value = values[key]
        return if (value.isNullOrEmpty()) null else value
    }
}
