import activePackJson from "../../../../packs/active.json"

export type PackKey =
    | "blank"
    | "paint"
    | "pong"
    | "snake"
    | "astro"
    | "asteroid"
    | "blackjack"
    | "chess"
    | "style"
    | "cabin"
    | "salon"
    | "sitter"
    | "code"
    | "ludo"
    | "gomoku"
    | "tawla"
    | "carrom"
    | "hanafuda"
    | "truco"
    | "race"
    | "chimney"
    | "link"
    | "folio"
    | "resume"
    | "fund-index"
    | "photography"
    | "photography-music"
    | "wedding"
    | "band"
    | "dj"
    | "single"
    | "services"
    | "services-emergency"
    | "services-recurring"
    | "church"
    | "nonprofit"
    | "community"
    | "estate"
    | "vows"
    | "gala"
    | "reunion"
    | "fitness"
    | "fitness-yoga"
    | "fitness-trainer"
    | "care"
    | "launch"
    | "blog"
    | "menu"
    | "flash"
    | "quiz"
    | "sugar"
    | "trade"
    | "chat"
    | "talk"
    | "auth"
    | "saas"
    | "accounting"
    | "cfo"
    | "credit"
    | "flow"
    | "pitch"
    | "shop"
    | "invoice"
    | "pdf"
    | "checkout"
    | "interpret"
    | "entry"
    | "quickbooks"
    | "agent"
    | "files"
    | "images"

export interface ActivePack {
    key: PackKey
}

/** Which pack owns `/` — mirrors packs/active.json (set on project create when a pack is applied). */
export const activePack = activePackJson as ActivePack
