// Generated by scripts/generate-native-theme.mjs from repobot.theme.json.
// Do not edit — change repobot.theme.json and run `npm run codegen`.

package com.baseapp.android.view.theme

object GeneratedTheme {
    // Brand accents (light / dark surfaces), derived like the web tokens.
    const val ACCENT_LIGHT = 0xFF1F6FEB
    const val ACCENT_TEXT_LIGHT = 0xFFFFFFFF
    const val ACCENT_DARK = 0xFF90CAF9
    const val ACCENT_TEXT_DARK = 0xFF071223

    // Corner radius scale ("soft"), in dp.
    const val RADIUS_SM = 6
    const val RADIUS_MD = 10
    const val RADIUS_LG = 14
    const val RADIUS_PILL = 999

    // Spacing scale ("comfortable"), in dp.
    const val SPACE_XXS = 2
    const val SPACE_XS = 4
    const val SPACE_SM = 8
    const val SPACE_MD = 12
    const val SPACE_LG = 16
    const val SPACE_XL = 24

    // Default UI mode from the contract ("system" follows the OS appearance).
    const val DEFAULT_MODE = "dark"

    // Font preset from the contract; resolved in view/theme/Theme.kt.
    const val FONT_FAMILY = "system"
}
