import Foundation

enum AppFlavor: String, CaseIterable {
  case sandbox
  case dev
  case prod

  static func resolve(infoDictionary: [String: Any] = Bundle.main.infoDictionary ?? [:]) -> AppFlavor {
    if
      let configuredValue = infoDictionary["Flavor"] as? String,
      let configuredFlavor = AppFlavor(rawValue: configuredValue.lowercased())
    {
      return configuredFlavor
    }

    // Fail closed to production if app flavor wiring is misconfigured.
    return .prod
  }
}

/// Mirrors AUTH_MODE / VITE_AUTH_MODE in env.manifest.json: 'local' uses the
/// bootstrap-generated dev JWT; 'builtin' uses the kernel's own auth API.
enum AuthMode: String {
  case local
  case builtin
}

struct AppConfig: Equatable {
  let flavor: AppFlavor
  /// Display name shown on the sign-in screen. Falls back to "App" when unset.
  let appName: String
  let graphqlURL: URL
  let authMode: AuthMode
  /// Enabled sign-in methods in render order, resolved from the AUTH_METHODS
  /// config value (comma-separated). Defaults to [.emailCode] when unset.
  let authMethods: [AuthMethod]
  /// Where OAuth callbacks land (custom URL scheme back into the app).
  let redirectURL: URL
  /// Sandbox only: the signed dev-principal JWT. Stamped into the built
  /// bundle by the "Stamp Sandbox Config" build phase from web/app/.env.local
  /// (generated by `npm run bootstrap:env`); empty in the committed plist.
  let localAuthToken: String?

  /// The auth API endpoint is the auth__request__api function, which lives
  /// next to the GraphQL function in every environment — the emulator and
  /// the platform deployer treat all exports uniformly — so its URL is the
  /// GraphQL URL with the trailing function name swapped.
  var authURL: URL? {
    let graphqlString = graphqlURL.absoluteString
    guard graphqlString.contains("graphql__request__api") else {
      return nil
    }
    let replaced = graphqlString.replacingOccurrences(
      of: "graphql__request__api",
      with: "auth__request__api"
    )
    return URL(string: replaced)
  }
}

enum ConfigLoaderError: Error, LocalizedError {
  case missingConfigFile(String)
  case invalidConfigShape
  case missingValue(String)
  case invalidURL(String)

  var errorDescription: String? {
    switch self {
    case let .missingConfigFile(name):
      return "Missing bundled config file: \(name)."
    case .invalidConfigShape:
      return "Environment config has an unexpected format."
    case let .missingValue(key):
      return "Missing configuration value for key: \(key)."
    case let .invalidURL(key):
      return "Invalid URL value for key: \(key)."
    }
  }
}

enum ConfigLoader {
  static func load(flavor: AppFlavor, bundle: Bundle = .main) throws -> AppConfig {
    let fileName = "Config.\(flavor.rawValue)"
    guard let fileURL = bundle.url(forResource: fileName, withExtension: "plist") else {
      throw ConfigLoaderError.missingConfigFile(fileName)
    }
    let data = try Data(contentsOf: fileURL)
    let rawObject = try PropertyListSerialization.propertyList(from: data, format: nil)
    guard let dictionary = rawObject as? [String: Any] else {
      throw ConfigLoaderError.invalidConfigShape
    }
    return try parse(
      flavor: flavor,
      dictionary: dictionary,
      isClientOnly: ActivePack.isClientOnly
    )
  }

  /// Client-only packs (blank, pong) build with an empty backend config —
  /// there is no backend to point the app at, and their surfaces never touch
  /// the network — so boot on a harmless local-mode placeholder instead of
  /// failing closed. When real values are stamped (an agent upgraded the
  /// project to a backend pack and redeployed), the strict path wins again.
  static func clientOnlyPlaceholder(
    flavor: AppFlavor,
    dictionary: [String: Any]
  ) -> AppConfig {
    AppConfig(
      flavor: flavor,
      appName: optionalString("APP_NAME", from: dictionary) ?? "App",
      graphqlURL: URL(string: "https://client-only.invalid/graphql")!,
      authMode: .local,
      authMethods: resolveAuthMethods(methodsValue: optionalString("AUTH_METHODS", from: dictionary)),
      redirectURL: optionalString("AUTH_REDIRECT_URL", from: dictionary)
        .flatMap(URL.init(string:)) ?? URL(string: "baseapp://auth/callback")!,
      localAuthToken: optionalString("LOCAL_AUTH_TOKEN", from: dictionary)
    )
  }

  static func parse(
    flavor: AppFlavor,
    dictionary: [String: Any],
    isClientOnly: Bool
  ) throws -> AppConfig {
    do {
      return try parse(flavor: flavor, dictionary: dictionary)
    } catch where isClientOnly {
      return clientOnlyPlaceholder(flavor: flavor, dictionary: dictionary)
    }
  }

  static func parse(flavor: AppFlavor, dictionary: [String: Any]) throws -> AppConfig {
    let graphqlRaw = try requiredString("GRAPHQL_URL", from: dictionary)
    let authModeRaw = try requiredString("AUTH_MODE", from: dictionary)
    let redirectRaw = try requiredString("AUTH_REDIRECT_URL", from: dictionary)
    let appName = optionalString("APP_NAME", from: dictionary) ?? "App"

    guard let graphqlURL = URL(string: graphqlRaw) else {
      throw ConfigLoaderError.invalidURL("GRAPHQL_URL")
    }
    guard let authMode = AuthMode(rawValue: authModeRaw.lowercased()) else {
      throw ConfigLoaderError.missingValue("AUTH_MODE")
    }
    guard let redirectURL = URL(string: redirectRaw) else {
      throw ConfigLoaderError.invalidURL("AUTH_REDIRECT_URL")
    }

    return AppConfig(
      flavor: flavor,
      appName: appName,
      graphqlURL: graphqlURL,
      authMode: authMode,
      authMethods: resolveAuthMethods(methodsValue: optionalString("AUTH_METHODS", from: dictionary)),
      redirectURL: redirectURL,
      localAuthToken: optionalString("LOCAL_AUTH_TOKEN", from: dictionary)
    )
  }

  private static func requiredString(_ key: String, from dictionary: [String: Any]) throws -> String {
    guard let value = dictionary[key] as? String, !value.isEmpty else {
      throw ConfigLoaderError.missingValue(key)
    }
    return value
  }

  private static func optionalString(_ key: String, from dictionary: [String: Any]) -> String? {
    guard let value = dictionary[key] as? String, !value.isEmpty else {
      return nil
    }
    return value
  }
}
