// The pack-switching engine for local template iteration, shared by the
// dev-pack CLI (scripts/dev-pack.sh) and the Template Studio dev middleware
// (web/app/dev/templateStudio.ts). Switching mirrors what compose-pack.sh
// does to a published template, scoped to what a running dev server can
// hot-apply:
//
//   - packs/active.json               which pack owns `/`
//   - catalog.theme                   merged over repobot.theme.json
//   - catalog.landing                 merged over repobot.landing.json
//   - packs/<key>/repobot.project.json stamped to the root + scaffold-ia run
//
// Pristine file contents are snapshotted to .dev/studio-overlay.json (local
// dev state, gitignored) before the first overlay write; every switch first
// restores them byte-for-byte, so switching back to `blank` leaves no git
// diff. The one exception is stub pages generated by the IA scaffolder:
// user code is never deleted, so they are tracked and reported instead
// (`git clean` removes them when you are done).
//
// CLI (what dev-pack.sh execs):
//   node scripts/lib/pack-switch.mjs            list packs, mark the active one
//   node scripts/lib/pack-switch.mjs <key>      switch to a pack
//   node scripts/lib/pack-switch.mjs --next     cycle alphabetically
//   node scripts/lib/pack-switch.mjs --prev

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { runScaffold } from "../scaffold-ia.mjs"

// The exact committed shape: writing this for `blank` leaves no git diff.
const PRISTINE_COMMENT =
    "Which pack owns `/` in this checkout. Project create will set this" +
    " when applying a pack overlay (blank = no template)."
const DEV_COMMENT =
    "Which pack owns `/` in this checkout. Set locally by scripts/dev-pack.sh" +
    " for template iteration — switch back with `npm run dev:pack -- blank`."

const THEME_FILE = "repobot.theme.json"
const LANDING_FILE = "repobot.landing.json"
const CONTENT_FILE = "repobot.content.json"
const PROJECT_FILE = "repobot.project.json"
const STATE_FILE = path.join(".dev", "studio-overlay.json")

/**
 * The scaffolder-wired files, snapshotted alongside the manifest so a
 * switch-back is byte-exact and so tests can read the raw kernel from the
 * overlay state while a pack is active. App.tsx and shellNavSections.tsx are
 * edited NON-convergently for a manifest with dashboard destinations (the
 * kernel's Projects/Users exemplar is stripped, which re-running against the
 * restored manifest cannot resurrect); Router.ts only carries convergent
 * managed blocks but rides along for the tests' benefit.
 */
const EXEMPLAR_FILES = [
    "web/app/src/App.tsx",
    "web/app/src/View/Navbar/shellNavSections.tsx",
    "web/app/src/Config/Router.ts",
]

/** Every pack with a catalog, sorted by key, catalog fields spread in. */
export function listPacks(repoRoot) {
    const packsDir = path.join(repoRoot, "packs")
    return readdirSync(packsDir, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .filter((key) => existsSync(path.join(packsDir, key, "catalog.json")))
        .sort()
        .map((key) => {
            // Resolve each entry so derived templates list with their base
            // pack's shape (base, capabilities, homePath, ...) under their own
            // identity — a raw remix catalog carries only identity + seed +
            // brand, which left consumers like the studio unable to group it.
            const catalog = resolveCatalog(repoRoot, {
                key,
                ...JSON.parse(readFileSync(path.join(packsDir, key, "catalog.json"), "utf8")),
            })
            catalog.hasProjectIa ??= existsSync(path.join(packsDir, catalog.activeKey, PROJECT_FILE))
            return catalog
        })
}

/**
 * Expand a derived-template catalog (`remixOf`, packs/README.md "Derived
 * templates") into the effective catalog every composer runs against: the
 * base pack's catalog with the remix's identity (key, templateKey, title,
 * description) on top, the remix brand merged over the base theme, and two
 * remix-only fields carried through —
 *
 *   activeKey    the BASE pack key: what packs/active.json and the native
 *                ActivePack constants must carry, because the kernel's
 *                routers and shells only know real packs. A composed remix
 *                IS the base pack, wearing different content and brand.
 *   contentSeed  the seed module the composer copies over the base pack's
 *                contentContract.module.
 *
 * Non-remix catalogs pass through with activeKey = key, so callers never
 * branch. The ONE expansion every composition path shares — switchPack
 * below, compose-pack.sh, and the design-manifest generator — for the same
 * reason applyPackOverlays is: a path that expands its own subset is how a
 * derived template would ship wearing the base brand.
 */
export function resolveCatalog(repoRoot, catalog) {
    if (catalog.remixOf === undefined) {
        return { ...catalog, activeKey: catalog.key }
    }
    const basePath = path.join(repoRoot, "packs", catalog.remixOf, "catalog.json")
    if (!existsSync(basePath)) {
        throw new Error(`remix '${catalog.key}': base pack '${catalog.remixOf}' has no catalog`)
    }
    const base = JSON.parse(readFileSync(basePath, "utf8"))
    if (base.remixOf !== undefined) {
        throw new Error(`remix '${catalog.key}': base '${catalog.remixOf}' is itself a remix`)
    }
    return {
        ...base,
        key: catalog.key,
        activeKey: base.key,
        remixOf: catalog.remixOf,
        contentSeed: catalog.contentSeed,
        templateKey: catalog.templateKey,
        title: catalog.title,
        ...(catalog.description !== undefined ? { description: catalog.description } : {}),
        ...(catalog.marketingExampleTitle !== undefined
            ? { marketingExampleTitle: catalog.marketingExampleTitle }
            : {}),
        ...(catalog.previewPath !== undefined ? { previewPath: catalog.previewPath } : {}),
        // Top-level theme merge: the remix's brand block replaces the base's
        // wholesale (a remix always declares both light and dark values).
        ...(base.theme || catalog.theme ? { theme: { ...base.theme, ...catalog.theme } } : {}),
        // Top-level landing merge: a remix may re-register the surface (its
        // `style` replaces the base's) while the base keeps the skeleton —
        // routes and page seeds are structure, and structure is the base's.
        ...(catalog.landing !== undefined ? { landing: { ...base.landing, ...catalog.landing } } : {}),
        // Top-level content merge: a remix may reseed a business domain (its
        // schedule replaces the base's wholesale) while unmentioned domains
        // stay the base's — the same per-key replacement as landing.
        ...(catalog.content !== undefined ? { content: { ...base.content, ...catalog.content } } : {}),
        // Form kinds merge the same way: a remix inherits the base's
        // formKey -> kind declarations (its forms ARE the base pack's
        // forms) and may re-kind or add keys of its own.
        ...(base.forms || catalog.forms ? { forms: { ...base.forms, ...catalog.forms } } : {}),
        hasProjectIa: existsSync(path.join(repoRoot, "packs", base.key, PROJECT_FILE)),
    }
}

/**
 * The key the checkout is presenting as. active.json carries the BASE key
 * (the app's routers only know real packs), so when a derived template is
 * active the switch state's activeRemix — recorded by switchPack — names
 * the remix actually being worn.
 */
export function readActiveKey(repoRoot) {
    const active = JSON.parse(readFileSync(path.join(repoRoot, "packs", "active.json"), "utf8")).key
    return readState(repoRoot).activeRemix ?? active
}

function readState(repoRoot) {
    const statePath = path.join(repoRoot, STATE_FILE)
    if (!existsSync(statePath)) {
        return { pristine: {}, scaffoldCreated: [] }
    }
    const state = JSON.parse(readFileSync(statePath, "utf8"))
    return {
        pristine: state.pristine ?? {},
        scaffoldCreated: state.scaffoldCreated ?? [],
        activeRemix: state.activeRemix,
    }
}

function writeState(repoRoot, state) {
    const statePath = path.join(repoRoot, STATE_FILE)
    if (Object.keys(state.pristine).length === 0 && state.scaffoldCreated.length === 0) {
        rmSync(statePath, { force: true })
        return
    }
    mkdirSync(path.dirname(statePath), { recursive: true })
    writeFileSync(statePath, JSON.stringify(state, null, 4) + "\n")
}

/** Scaffold-generated stub files recorded across switches (never auto-deleted). */
export function readScaffoldCreated(repoRoot) {
    return readState(repoRoot).scaffoldCreated.filter((file) => existsSync(path.join(repoRoot, file)))
}

/** Shallow top-level merge — THE overlay merge, shared by every composer.
 * `dropKeys` removes base keys the overlay deliberately supersedes (the
 * landing merge drops the kernel default's root `sections` for page-based
 * surfaces). */
function mergeOverlay(repoRoot, relativePath, overlay, dropKeys = []) {
    const filePath = path.join(repoRoot, relativePath)
    const merged = { ...JSON.parse(readFileSync(filePath, "utf8")), ...overlay }
    for (const key of dropKeys) {
        if (!(key in overlay)) delete merged[key]
    }
    writeFileSync(filePath, JSON.stringify(merged, null, 4) + "\n")
}

/**
 * Apply a pack catalog's compose-time overlays (theme merged over
 * repobot.theme.json, landing merged over repobot.landing.json, content
 * merged over repobot.content.json) to a tree. The ONE implementation every
 * composition path runs: the dev/studio switch (below), compose-pack.sh
 * staging a published template, and the preview builder — a path that
 * applies a subset is how photography's previews shipped rendering the
 * kernel default register instead of its own.
 */
export function applyPackOverlays(treeRoot, catalog) {
    const applied = { theme: false, landing: false, content: false }
    // The pack stamp: the key packs/active.json carries while this document
    // is live — the BASE key for a remix, matching what switchPack and
    // compose-pack.sh write there. The kernel resolvers
    // (landingDocument.ts, themeConfig.ts) treat a document stamped for a
    // foreign pack as absent, so an overlaid document must always identify
    // the pack it was composed for.
    const stampKey = catalog.activeKey ?? catalog.key
    if (catalog.theme) {
        mergeOverlay(treeRoot, THEME_FILE, { ...catalog.theme, pack: stampKey })
        applied.theme = true
    }
    if (catalog.content) {
        // The business-content contract: each catalog domain (schedule, ...)
        // replaces the kernel default's wholesale — facts don't part-merge.
        // The catalog's $comment stays in the catalog; the document keeps
        // the kernel default's own comment.
        const { $comment: _comment, ...domains } = catalog.content
        mergeOverlay(treeRoot, CONTENT_FILE, domains)
        applied.content = true
    }
    if (catalog.landing) {
        mergeOverlay(
            treeRoot,
            LANDING_FILE,
            { ...catalog.landing, pack: stampKey },
            // A page-based landing surface must not inherit the kernel
            // default's root skeleton (nothing renders it; its phantom
            // sections would leak into the layout tooling).
            catalog.landing.sections === undefined &&
                (catalog.landing.pages !== undefined || catalog.landing.routes !== undefined)
                ? ["sections"]
                : [],
        )
        applied.landing = true
    }
    return applied
}

/**
 * Switch the checkout to a pack: restore whatever the previous switch
 * overlaid, then apply the new pack's active.json + overlays. Throws on an
 * unknown key or a scaffold collision (nothing is partially applied before
 * the scaffold runs; a collision leaves the manifest stamped for inspection).
 */
export function switchPack(repoRoot, key) {
    const packs = listPacks(repoRoot)
    const raw = packs.find((candidate) => candidate.key === key)
    if (!raw) {
        throw new Error(`unknown pack '${key}'. Known packs: ${packs.map((p) => p.key).join(", ")}`)
    }
    // A derived template resolves to its base pack wearing the remix's brand
    // and content seed; everything below runs against the effective catalog.
    const pack = resolveCatalog(repoRoot, raw)

    const state = readState(repoRoot)
    // Remember which remix the checkout is wearing (readActiveKey above);
    // undefined for real packs, and JSON.stringify drops it from the file.
    state.activeRemix = pack.key === pack.activeKey ? undefined : pack.key

    // 1. Restore the pristine files the previous switch overlaid. When the
    //    project manifest comes back, re-run the scaffolder so the managed
    //    <ia:*> blocks in Router/App/nav converge back too (it is a pure
    //    function of the manifest; stub pages are left alone).
    let restoredProject = false
    for (const [relativePath, content] of Object.entries(state.pristine)) {
        writeFileSync(path.join(repoRoot, relativePath), content)
        if (relativePath === PROJECT_FILE) restoredProject = true
    }
    state.pristine = {}
    if (restoredProject) {
        runScaffold(repoRoot)
    }

    // 2. active.json — the dev server's manifest watcher picks this up and
    //    reloads the app on its own. A remix stamps its BASE key: the app's
    //    pack switch only knows real packs.
    const activeBody = {
        key: pack.activeKey,
        comment: pack.activeKey === "blank" ? PRISTINE_COMMENT : DEV_COMMENT,
    }
    writeFileSync(
        path.join(repoRoot, "packs", "active.json"),
        JSON.stringify(activeBody, null, 4) + "\n",
    )

    const snapshot = (relativePath) => {
        state.pristine[relativePath] = readFileSync(path.join(repoRoot, relativePath), "utf8")
    }

    // 3. Theme + landing overlays (hot-applied by the dev server: the theme
    //    rides the theme-contract HMR event, the landing document propagates
    //    through landingDocument.ts). Snapshot first — the switch is
    //    reversible where a compose is not — then run the shared composer.
    if (pack.theme) snapshot(THEME_FILE)
    if (pack.landing) snapshot(LANDING_FILE)
    if (pack.content) snapshot(CONTENT_FILE)
    const applied = { ...applyPackOverlays(repoRoot, pack), projectIa: false, contentSeed: false }

    // 3b. A derived template's content seed replaces the base pack's content
    //     module — snapshotted first, so switching away restores the demo
    //     business byte-for-byte like every other overlay.
    if (pack.contentSeed !== undefined) {
        const module = pack.contentContract.module
        snapshot(module)
        writeFileSync(
            path.join(repoRoot, module),
            readFileSync(path.join(repoRoot, pack.contentSeed), "utf8"),
        )
        applied.contentSeed = true
    }

    // 4. Pack-owned project IA: stamp the manifest and scaffold, the same
    //    convergence compose-pack.sh runs for the published template.
    let scaffoldSummary
    if (pack.hasProjectIa) {
        snapshot(PROJECT_FILE)
        for (const relativePath of EXEMPLAR_FILES) {
            snapshot(relativePath)
        }
        // activeKey, not key: a derived template's project IA (like all its
        // structure) lives in its base pack's directory.
        const packManifest = path.join(repoRoot, "packs", pack.activeKey, PROJECT_FILE)
        writeFileSync(path.join(repoRoot, PROJECT_FILE), readFileSync(packManifest, "utf8"))
        try {
            const { summary } = runScaffold(repoRoot)
            scaffoldSummary = summary
        } finally {
            writeState(repoRoot, state)
        }
        applied.projectIa = true
        for (const file of scaffoldSummary.createdFiles) {
            if (!state.scaffoldCreated.includes(file)) {
                state.scaffoldCreated.push(file)
            }
        }
    }

    writeState(repoRoot, state)
    return {
        pack,
        applied,
        scaffoldSummary,
        scaffoldCreated: readScaffoldCreated(repoRoot),
    }
}

function main() {
    const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..")
    const arg = process.argv[2] || ""

    const packs = listPacks(repoRoot)
    const active = readActiveKey(repoRoot)

    // dev-up records the port it actually bound (it auto-bumps past ports
    // owned by other processes), so read that instead of assuming 5173.
    const portFile = path.join(repoRoot, ".dev", "web-port")
    const port =
        process.env.PORT ||
        (existsSync(portFile) ? readFileSync(portFile, "utf8").trim() : "") ||
        "5173"

    const report = (result) => {
        const { pack, applied, scaffoldSummary, scaffoldCreated } = result
        const url = `http://127.0.0.1:${port}${pack.homePath || "/"}`
        console.log(`Active pack: ${pack.key} (${pack.title ?? pack.templateKey})`)
        console.log(`  home view:  ${pack.homeViewDir}`)
        console.log(`  local url:  ${url}`)
        if (pack.previewPath && pack.previewPath !== pack.homePath) {
            console.log(`  preview:    http://127.0.0.1:${port}${pack.previewPath}`)
        }
        if (applied.theme) console.log("  applied the pack's theme overlay to repobot.theme.json")
        if (applied.landing) console.log("  applied the pack's landing overlay to repobot.landing.json")
        if (applied.content) console.log("  applied the pack's content seed to repobot.content.json")
        if (applied.contentSeed) {
            console.log(`  copied the remix content seed over ${pack.contentContract.module}`)
        }
        if (applied.projectIa) {
            console.log("  stamped the pack's repobot.project.json and ran the IA scaffolder")
            for (const file of scaffoldSummary?.createdFiles ?? []) {
                console.log(`    created ${file}`)
            }
        }
        if (scaffoldCreated.length > 0) {
            console.log("  scaffold-generated stub files in the tree (git clean removes them):")
            for (const file of scaffoldCreated) console.log(`    ${file}`)
        }
        console.log("A running dev server (npm run dev:up) reloads on its own.")
        console.log(`Template Studio: http://127.0.0.1:${port}/__studio`)
    }

    if (!arg) {
        console.log(`Packs (${packs.length}); active marked with *:\n`)
        for (const pack of packs) {
            const marker = pack.key === active ? "*" : " "
            const title = pack.title ?? pack.templateKey ?? ""
            console.log(`  ${marker} ${pack.key.padEnd(10)} ${title}`)
        }
        console.log(`\nSwitch: npm run dev:pack -- <key>   Cycle: npm run dev:pack -- --next`)
        console.log(`Or browse them all: http://127.0.0.1:${port}/__studio`)
        return
    }

    if (arg === "--next" || arg === "--prev") {
        const index = packs.findIndex((pack) => pack.key === active)
        const step = arg === "--next" ? 1 : -1
        const next = packs[(index + step + packs.length) % packs.length]
        report(switchPack(repoRoot, next.key))
        return
    }

    try {
        report(switchPack(repoRoot, arg))
    } catch (error) {
        console.error(`error: ${error.message}`)
        process.exit(1)
    }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    main()
}
