package com.baseapp.android.auth

import com.baseapp.android.config.AppConfig

/**
 * Sandbox-flavor auth client, mirroring web/core's LocalAuthClient: signs in
 * with the dev-principal JWT generated by `npm run bootstrap:env` and stamped
 * into the built APK by StampSandboxConfigTask. Local dev tokens never expire
 * server-side, so no refresh is needed.
 */
class LocalAuthClient(
    private val config: AppConfig,
    private val sessionStorage: SessionStorage,
) : AuthClient {

    override suspend fun restoreSession(): AuthSession? = sessionStorage.loadSession()

    override suspend fun signInLocal(): AuthSession {
        val token = config.localAuthToken
        if (token.isNullOrEmpty()) {
            throw AuthClientException(
                "No local dev token in the app. Run `npm run bootstrap:env` at the repo root,"
                    + " then rebuild the sandbox flavor."
            )
        }
        val session = AuthSession(
            accessToken = token,
            refreshToken = null,
            expiresAtEpochMs = null,
            email = "dev@local",
        )
        sessionStorage.persistSession(session)
        return session
    }

    override suspend fun sendEmailCode(email: String) {
        throw AuthClientException("Email sign-in is not available in local auth mode.")
    }

    override suspend fun verifyEmailCode(email: String, code: String): AuthSession {
        throw AuthClientException("Email sign-in is not available in local auth mode.")
    }

    override suspend fun signInWithPassword(email: String, password: String): AuthSession {
        throw AuthClientException("Password sign-in is not available in local auth mode.")
    }

    override suspend fun signUpWithPassword(email: String, password: String): AuthSession? {
        throw AuthClientException("Password sign-up is not available in local auth mode.")
    }

    override suspend fun requestPasswordReset(email: String) {
        throw AuthClientException("Password reset is not available in local auth mode.")
    }

    override suspend fun completePasswordReset(
        email: String,
        code: String,
        newPassword: String,
    ): AuthSession {
        throw AuthClientException("Password reset is not available in local auth mode.")
    }

    override suspend fun signInAnonymously(): AuthSession {
        throw AuthClientException("Anonymous sign-in is not available in local auth mode.")
    }

    override fun oauthAuthorizeUrl(provider: AuthMethod): String? {
        // OAuth flows need a remote auth server; the sandbox sign-in screen
        // simulates the flow by signing in as the local dev user instead.
        return null
    }

    override suspend fun handleIncomingUrl(url: String): AuthSession? {
        // Local auth does not depend on browser callbacks.
        return null
    }

    override suspend fun signOut() {
        sessionStorage.clearSession()
    }
}
