// Generate .env.local files for every package from env.manifest.json.
// - Existing .env.local files are left untouched (idempotent).
// - Values already present in the process environment (e.g. injected by the
//   Repobot sandbox) win over manifest defaults.
// - "generate" vars get fresh random values per checkout; the local dev-auth
//   token is signed here so the web client and functions agree on the secret.
import crypto from "node:crypto"
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const manifest = JSON.parse(readFileSync(path.join(repoRoot, "env.manifest.json"), "utf8"))

const generated = new Map()

function base64url(input) {
    return Buffer.from(input).toString("base64url")
}

function signLocalAuthToken(secretHex) {
    // Mirrors the claim shape minted by the built-in auth service, so the
    // backend principal-hydration path is identical in local mode.
    const header = { alg: "HS256", typ: "JWT" }
    const nowSeconds = Math.floor(Date.now() / 1000)
    const payload = {
        iss: "repobot-base-local",
        aud: "authenticated",
        sub: "local-dev-user",
        email: "dev@local.test",
        role: "authenticated",
        iat: nowSeconds,
        exp: nowSeconds + 60 * 60 * 24 * 365,
    }
    const signingInput = `${base64url(JSON.stringify(header))}.${base64url(JSON.stringify(payload))}`
    const signature = crypto
        .createHmac("sha256", Buffer.from(secretHex, "hex"))
        .update(signingInput)
        .digest("base64url")
    return `${signingInput}.${signature}`
}

// Values in already-written .env.local files win over fresh generation, so a
// partial re-bootstrap (e.g. one package's file was deleted) stays consistent
// with the surviving files. Without this the web token could be signed with a
// different secret than the one the functions verifier loads.
function existingValueFor(name) {
    for (const pkg of new Set(manifest.vars.map((v) => v.package))) {
        const envPath = path.join(repoRoot, pkg, ".env.local")
        if (!existsSync(envPath)) continue
        for (const line of readFileSync(envPath, "utf8").split("\n")) {
            if (line.startsWith(`${name}=`)) return line.slice(name.length + 1)
        }
    }
    return undefined
}

function valueFor(varDef) {
    if (process.env[varDef.name] !== undefined && process.env[varDef.name] !== "") {
        return process.env[varDef.name]
    }
    if (varDef.generate === "random-hex-32") {
        if (!generated.has(varDef.name)) {
            const existing = existingValueFor(varDef.name)
            generated.set(varDef.name, existing ?? crypto.randomBytes(32).toString("hex"))
        }
        return generated.get(varDef.name)
    }
    if (varDef.generate === "local-auth-token") {
        const secretDef = manifest.vars.find((v) => v.name === "LOCAL_AUTH_SECRET")
        const secret = valueFor(secretDef)
        generated.set("LOCAL_AUTH_SECRET", secret)
        return signLocalAuthToken(secret)
    }
    return varDef.localDefault
}

const packages = [...new Set(manifest.vars.map((v) => v.package))]
for (const pkg of packages) {
    const envPath = path.join(repoRoot, pkg, ".env.local")
    if (existsSync(envPath)) {
        console.log(`[bootstrap-env] ${pkg}/.env.local exists; leaving it alone.`)
        continue
    }
    const vars = manifest.vars.filter((v) => v.package === pkg && v.environments.includes("local"))
    const lines = [
        "# Generated by `npm run bootstrap:env` from env.manifest.json. Safe to edit;",
        "# delete this file and re-run bootstrap to regenerate defaults.",
        ...vars.map((v) => `${v.name}=${valueFor(v) ?? ""}`),
    ]
    writeFileSync(envPath, lines.join("\n") + "\n")
    console.log(`[bootstrap-env] Wrote ${pkg}/.env.local (${vars.length} vars).`)
}
