import Foundation

enum LocalAuthClientError: Error, LocalizedError {
  case missingDevToken
  case notAvailable
  /// A remote-only method (password, OAuth, guest...) was called in local
  /// auth mode; the label names the method for the error message.
  case remoteMethodUnavailable(String)

  var errorDescription: String? {
    switch self {
    case .missingDevToken:
      return "No local dev token in the app bundle. Run `npm run bootstrap:env` at the repo root, then rebuild the Sandbox scheme."
    case .notAvailable:
      return "Email sign-in is not available in local auth mode."
    case let .remoteMethodUnavailable(label):
      return "\(label) is not available in local auth mode."
    }
  }
}

/// Sandbox-flavor auth client, mirroring web/core's LocalAuthClient: signs in
/// with the dev-principal JWT generated by `npm run bootstrap:env` and stamped
/// into Config.sandbox.plist by the "Stamp Sandbox Config" build phase. Local
/// dev tokens never expire server-side, so no refresh is needed.
@MainActor
final class LocalAuthClient: AuthClient {
  private let config: AppConfig
  private let sessionStorage: SessionStorage

  init(config: AppConfig, sessionStorage: SessionStorage = UserDefaultsSessionStorage()) {
    self.config = config
    self.sessionStorage = sessionStorage
  }

  func restoreSession() async -> AuthSession? {
    sessionStorage.loadSession()
  }

  func signInLocal() async throws -> AuthSession {
    guard let token = config.localAuthToken, !token.isEmpty else {
      throw LocalAuthClientError.missingDevToken
    }
    let session = AuthSession(
      accessToken: token,
      refreshToken: nil,
      expiresAt: nil,
      email: "dev@local"
    )
    sessionStorage.persistSession(session)
    return session
  }

  func sendEmailCode(email _: String) async throws {
    throw LocalAuthClientError.notAvailable
  }

  func verifyEmailCode(email _: String, code _: String) async throws -> AuthSession {
    throw LocalAuthClientError.notAvailable
  }

  // Remote-only methods all throw: in sandbox mode the sign-in screen
  // simulates these flows and signs in via signInLocal instead, mirroring
  // web/core's LocalAuthClient.

  func signInWithPassword(email _: String, password _: String) async throws -> AuthSession {
    throw LocalAuthClientError.remoteMethodUnavailable("Password sign-in")
  }

  func signUpWithPassword(email _: String, password _: String) async throws -> AuthSession? {
    throw LocalAuthClientError.remoteMethodUnavailable("Password sign-up")
  }

  func requestPasswordReset(email _: String) async throws {
    throw LocalAuthClientError.remoteMethodUnavailable("Password reset")
  }

  func completePasswordReset(email _: String, code _: String, newPassword _: String) async throws -> AuthSession {
    throw LocalAuthClientError.remoteMethodUnavailable("Password reset")
  }

  func signInAnonymously() async throws -> AuthSession {
    throw LocalAuthClientError.remoteMethodUnavailable("Anonymous sign-in")
  }

  func signInWithApple(identityToken _: String, fullName _: String?) async throws -> AuthSession {
    throw LocalAuthClientError.remoteMethodUnavailable("Apple sign-in")
  }

  func oauthAuthorizeURL(provider _: AuthMethod) -> URL? {
    // OAuth needs a real authorize endpoint; local mode has none.
    nil
  }

  func handleIncomingURL(_: URL) async -> AuthSession? {
    // Local auth does not depend on browser callbacks.
    nil
  }

  func fetchRuntimeAuthMethods() async -> [AuthMethod]? {
    // No runtime config in local mode; build-time methods apply.
    nil
  }

  // In local (sandbox) auth mode there is no second factor to manage.

  var hasPendingMfaChallenge: Bool {
    false
  }

  func verifyMfaCode(_: String) async throws -> AuthSession {
    throw LocalAuthClientError.remoteMethodUnavailable("Two-factor authentication")
  }

  func enrollMfa() async throws -> MfaEnrollment {
    throw LocalAuthClientError.remoteMethodUnavailable("Two-factor authentication")
  }

  func confirmMfa(code _: String) async throws -> [String] {
    throw LocalAuthClientError.remoteMethodUnavailable("Two-factor authentication")
  }

  func disableMfa(code _: String) async throws {
    throw LocalAuthClientError.remoteMethodUnavailable("Two-factor authentication")
  }

  func fetchMfaEnabled() async -> Bool {
    false
  }

  func signOut() async {
    sessionStorage.clearSession()
  }
}
