// Generated by scripts/generate-native-theme.mjs from repobot.theme.json.
// Do not edit — change repobot.theme.json and run `npm run codegen`.

import CoreGraphics

enum GeneratedTheme {
  // Brand accents (light / dark surfaces), derived like the web tokens.
  static let accentLight = "#1f6feb"
  static let accentTextLight = "#ffffff"
  static let accentDark = "#90caf9"
  static let accentTextDark = "#071223"

  // Corner radius scale ("soft").
  static let radiusSm: CGFloat = 6
  static let radiusMd: CGFloat = 10
  static let radiusLg: CGFloat = 14
  static let radiusPill: CGFloat = 999

  // Spacing scale ("comfortable").
  static let spaceXxs: CGFloat = 2
  static let spaceXs: CGFloat = 4
  static let spaceSm: CGFloat = 8
  static let spaceMd: CGFloat = 12
  static let spaceLg: CGFloat = 16
  static let spaceXl: CGFloat = 24

  // Default UI mode from the contract ("system" follows the OS appearance).
  static let defaultMode = "dark"

  // Font preset from the contract; resolved in View/Theme/Theme.swift.
  static let fontFamily = "system"
}
